version: "3.9"

services:
  api1:
    build:
      context: ./ConsoleApp1/ConsoleApp1.Service
    ports:
      - "8080:8080"
    depends_on:
      - api2

  api2:
    build:
      context: ./ConsoleApp2/ConsoleApp2.Service
    ports:
      - "8081:8080"